FROM golang:alpine


WORKDIR /go/src/github.com/vasarostik/go_blog/

RUN apk update
RUN apk upgrade
RUN apk add bash
RUN apk add curl
RUN apk add --no-cache \
        libc6-compat

COPY ./package/api ./package/api
COPY ./package/migration ./package/migration
COPY ./migration.sh ./

#CMD ["sleep","50000"]
RUN chmod +x migration.sh
#RUN ls
#RUN go build -o ./cmd/api/api ./cmd/api
#RUN go build -o ./cmd/migration/migration ./cmd/migration

