FROM golang:alpine

WORKDIR /go/src/github.com/vasarostik/go_blog/

RUN apk add --no-cache \
        libc6-compat

COPY ./dockerfiles/api ./dockerfiles/api
COPY ./dockerfiles/migration ./dockerfiles/migration
COPY ./swagger ./swagger
COPY ./migration.sh ./
COPY ./dockerfiles/configManager/conf.local.yaml ./dockerfiles/configManager/conf.local.yaml
COPY ./azure.env ./azure.env

RUN chmod +x migration.sh

