FROM golang:alpine

WORKDIR /go/src/github.com/vasarostik/go_blog/

RUN apk add --no-cache \
        libc6-compat

COPY ./dockerfiles/grpc ./dockerfiles/grpc
COPY ./dockerfiles/configManager/conf.local.yaml ./dockerfiles/configManager/conf.local.yaml
COPY ./azure.env ./azure.env


