FROM golang:alpine


WORKDIR /go/src/github.com/vasarostik/go_blog/

RUN apk add --no-cache \
        libc6-compat

COPY ./dockerfiles/nats ./dockerfiles/nats
COPY ./dockerfiles/configManager/conf.local.yaml ./dockerfiles/configManager/conf.local.yaml



